const states = [
  { title: 'AC', value: 1 },
  { title: 'AL', value: 2 },
  { title: 'AP', value: 3 },
  { title: 'BA', value: 4 },
  { title: 'CE', value: 5 },
  { title: 'DF', value: 6 },
  { title: 'ES', value: 7 },
  { title: 'GO', value: 8 },
  { title: 'MA', value: 9 },
  { title: 'MT', value: 10 },
  { title: 'MS', value: 11 },
  { title: 'MG', value: 12 },
  { title: 'PA', value: 13 },
  { title: 'PB', value: 14 },
  { title: 'PR', value: 15 },
  { title: 'PE', value: 16 },
  { title: 'PI', value: 17 },
  { title: 'RJ', value: 18 },
  { title: 'RN', value: 19 },
  { title: 'RS', value: 20 },
  { title: 'RO', value: 21 },
  { title: 'RR', value: 22 },
  { title: 'SC', value: 23 },
  { title: 'SP', value: 24 },
  { title: 'SE', value: 25 },
  { title: 'TO', value: 26 },
];

export default states;
